POST http://localhost:3013/api/blogs
Content-Type: application/json

{
    "title": "controllerin lisäys",
    "author": "Antero Oikkonen",
    "url": "https://fullstack-hy.github.io/osa4/",
    "likes": "0"
}